//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileBook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileBook.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support this feature..
        /// </summary>
        internal static string AddEditAlert {
            get {
                return ResourceManager.GetString("AddEditAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo with the camera.
        /// </summary>
        internal static string AddEditCamera {
            get {
                return ResourceManager.GetString("AddEditCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete picture.
        /// </summary>
        internal static string AddEditDelete {
            get {
                return ResourceManager.GetString("AddEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog.
        /// </summary>
        internal static string AddEditDialog {
            get {
                return ResourceManager.GetString("AddEditDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick at Galery.
        /// </summary>
        internal static string AddEditGalery {
            get {
                return ResourceManager.GetString("AddEditGalery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AddNamePlaceholder {
            get {
                return ResourceManager.GetString("AddNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string AddNickNamePlaceholder {
            get {
                return ResourceManager.GetString("AddNickNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        internal static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already token..
        /// </summary>
        internal static string AuthorizationAlert {
            get {
                return ResourceManager.GetString("AuthorizationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want delete profile?.
        /// </summary>
        internal static string MainListAlertDelete {
            get {
                return ResourceManager.GetString("MainListAlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MainListAlertDeleteNo {
            get {
                return ResourceManager.GetString("MainListAlertDeleteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MainListAlertDeleteYes {
            get {
                return ResourceManager.GetString("MainListAlertDeleteYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles added..
        /// </summary>
        internal static string MainListLabelText {
            get {
                return ResourceManager.GetString("MainListLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main List.
        /// </summary>
        internal static string MainListTitle {
            get {
                return ResourceManager.GetString("MainListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOBACK.
        /// </summary>
        internal static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by date.
        /// </summary>
        internal static string SettingsLabelDate {
            get {
                return ResourceManager.GetString("SettingsLabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        internal static string SettingsLabelName {
            get {
                return ResourceManager.GetString("SettingsLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by nick name.
        /// </summary>
        internal static string SettingsLabelNickName {
            get {
                return ResourceManager.GetString("SettingsLabelNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Russian.
        /// </summary>
        internal static string SettingsLabelRussian {
            get {
                return ResourceManager.GetString("SettingsLabelRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate dark theme.
        /// </summary>
        internal static string SettingsLabelTheme {
            get {
                return ResourceManager.GetString("SettingsLabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Ukrainian.
        /// </summary>
        internal static string SettingsLabelUkrainian {
            get {
                return ResourceManager.GetString("SettingsLabelUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings View.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password..
        /// </summary>
        internal static string SignInAlert {
            get {
                return ResourceManager.GetString("SignInAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignInLabelText {
            get {
                return ResourceManager.GetString("SignInLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SignInLoginPlaceholder {
            get {
                return ResourceManager.GetString("SignInLoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignInPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SignInPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Signin.
        /// </summary>
        internal static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignUpButtonText {
            get {
                return ResourceManager.GetString("SignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string SignUpConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SignUpConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SignUpLoginPlaceholder {
            get {
                return ResourceManager.GetString("SignUpLoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUpPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SignUpPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Signup.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First simbol must not digit in login..
        /// </summary>
        internal static string ValidatorFirst {
            get {
                return ResourceManager.GetString("ValidatorFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number, uppercase or lowercase letter..
        /// </summary>
        internal static string ValidatorMust {
            get {
                return ResourceManager.GetString("ValidatorMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of characters less than 4 or more than 16..
        /// </summary>
        internal static string ValidatorNumberLogin {
            get {
                return ResourceManager.GetString("ValidatorNumberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of characters less than 8 or more than 16..
        /// </summary>
        internal static string ValidatorNumberPassword {
            get {
                return ResourceManager.GetString("ValidatorNumberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password are not equal..
        /// </summary>
        internal static string ValidatorPassword {
            get {
                return ResourceManager.GetString("ValidatorPassword", resourceCulture);
            }
        }
    }
}
